version: '2.24.6-desktop.1'

services:
  zookeeper:
      image: zookeeper@sha256:cacdaf98d6b0c622937168f879ae1ee5eeb4e3b3414da88c7b3dcdbe97fbc13b
      container_name: journal-zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - "2181:2181"
  kafka:
      depends_on:
          - zookeeper
      image: confluentinc/cp-kafka:7.4.4
      container_name: journal-kafka
      ports:
        - "29092:29092"
      environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


